/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as GamesIndexRouteImport } from './routes/games/index';
import { Route as GamesPacManRouteImport } from './routes/games/pac-man';
import { Route as GamesMustachioRouteImport } from './routes/games/mustachio';
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const GamesIndexRoute = GamesIndexRouteImport.update({
    id: '/games/',
    path: '/games/',
    getParentRoute: () => rootRouteImport,
});
const GamesPacManRoute = GamesPacManRouteImport.update({
    id: '/games/pac-man',
    path: '/games/pac-man',
    getParentRoute: () => rootRouteImport,
});
const GamesMustachioRoute = GamesMustachioRouteImport.update({
    id: '/games/mustachio',
    path: '/games/mustachio',
    getParentRoute: () => rootRouteImport,
});
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    GamesMustachioRoute: GamesMustachioRoute,
    GamesPacManRoute: GamesPacManRoute,
    GamesIndexRoute: GamesIndexRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
