/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UtilitiesQrCodeGeneratorRouteImport } from './routes/utilities/qr-code-generator'
import { Route as GamesPacManRouteImport } from './routes/games/pac-man'
import { Route as GamesMustachioRouteImport } from './routes/games/mustachio'
import { Route as GamesMazeGameRouteImport } from './routes/games/maze-game'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilitiesQrCodeGeneratorRoute =
  UtilitiesQrCodeGeneratorRouteImport.update({
    id: '/utilities/qr-code-generator',
    path: '/utilities/qr-code-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const GamesPacManRoute = GamesPacManRouteImport.update({
  id: '/games/pac-man',
  path: '/games/pac-man',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesMustachioRoute = GamesMustachioRouteImport.update({
  id: '/games/mustachio',
  path: '/games/mustachio',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesMazeGameRoute = GamesMazeGameRouteImport.update({
  id: '/games/maze-game',
  path: '/games/maze-game',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/maze-game': typeof GamesMazeGameRoute
  '/games/mustachio': typeof GamesMustachioRoute
  '/games/pac-man': typeof GamesPacManRoute
  '/utilities/qr-code-generator': typeof UtilitiesQrCodeGeneratorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/maze-game': typeof GamesMazeGameRoute
  '/games/mustachio': typeof GamesMustachioRoute
  '/games/pac-man': typeof GamesPacManRoute
  '/utilities/qr-code-generator': typeof UtilitiesQrCodeGeneratorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games/maze-game': typeof GamesMazeGameRoute
  '/games/mustachio': typeof GamesMustachioRoute
  '/games/pac-man': typeof GamesPacManRoute
  '/utilities/qr-code-generator': typeof UtilitiesQrCodeGeneratorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games/maze-game'
    | '/games/mustachio'
    | '/games/pac-man'
    | '/utilities/qr-code-generator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games/maze-game'
    | '/games/mustachio'
    | '/games/pac-man'
    | '/utilities/qr-code-generator'
  id:
    | '__root__'
    | '/'
    | '/games/maze-game'
    | '/games/mustachio'
    | '/games/pac-man'
    | '/utilities/qr-code-generator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesMazeGameRoute: typeof GamesMazeGameRoute
  GamesMustachioRoute: typeof GamesMustachioRoute
  GamesPacManRoute: typeof GamesPacManRoute
  UtilitiesQrCodeGeneratorRoute: typeof UtilitiesQrCodeGeneratorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities/qr-code-generator': {
      id: '/utilities/qr-code-generator'
      path: '/utilities/qr-code-generator'
      fullPath: '/utilities/qr-code-generator'
      preLoaderRoute: typeof UtilitiesQrCodeGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/pac-man': {
      id: '/games/pac-man'
      path: '/games/pac-man'
      fullPath: '/games/pac-man'
      preLoaderRoute: typeof GamesPacManRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/mustachio': {
      id: '/games/mustachio'
      path: '/games/mustachio'
      fullPath: '/games/mustachio'
      preLoaderRoute: typeof GamesMustachioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/maze-game': {
      id: '/games/maze-game'
      path: '/games/maze-game'
      fullPath: '/games/maze-game'
      preLoaderRoute: typeof GamesMazeGameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesMazeGameRoute: GamesMazeGameRoute,
  GamesMustachioRoute: GamesMustachioRoute,
  GamesPacManRoute: GamesPacManRoute,
  UtilitiesQrCodeGeneratorRoute: UtilitiesQrCodeGeneratorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
