/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesPacManRouteImport } from './routes/games/pac-man'
import { Route as GamesMustachioRouteImport } from './routes/games/mustachio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesPacManRoute = GamesPacManRouteImport.update({
  id: '/games/pac-man',
  path: '/games/pac-man',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesMustachioRoute = GamesMustachioRouteImport.update({
  id: '/games/mustachio',
  path: '/games/mustachio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/mustachio': typeof GamesMustachioRoute
  '/games/pac-man': typeof GamesPacManRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/mustachio': typeof GamesMustachioRoute
  '/games/pac-man': typeof GamesPacManRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games/mustachio': typeof GamesMustachioRoute
  '/games/pac-man': typeof GamesPacManRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/games/mustachio' | '/games/pac-man'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/games/mustachio' | '/games/pac-man'
  id: '__root__' | '/' | '/games/mustachio' | '/games/pac-man'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesMustachioRoute: typeof GamesMustachioRoute
  GamesPacManRoute: typeof GamesPacManRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/pac-man': {
      id: '/games/pac-man'
      path: '/games/pac-man'
      fullPath: '/games/pac-man'
      preLoaderRoute: typeof GamesPacManRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/mustachio': {
      id: '/games/mustachio'
      path: '/games/mustachio'
      fullPath: '/games/mustachio'
      preLoaderRoute: typeof GamesMustachioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesMustachioRoute: GamesMustachioRoute,
  GamesPacManRoute: GamesPacManRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
