name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: ['main']

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          cache: 'pnpm'
          cache-dependency-path: './frontend/pnpm-lock.yaml'

      - name: Cache Turbo
        uses: actions/cache@v5
        with:
          path: ./frontend/.turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('frontend/pnpm-lock.yaml', 'frontend/turbo.json', 'frontend/**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Prepare for deployment
        run: |
          pnpm deploy

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./frontend/app/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
